name: Build docker image and run node tests

on:
  push:
    branches: [ develop, main, fractasy_state_root_map ]

jobs:
  build-docker:
    runs-on: [self-hosted, linux, X64, hc]

    outputs:
      sha_short: ${{ steps.setvars.outputs.sha_short }}
      tag: ${{ steps.setvars.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set variables
        id: setvars
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Submodule init
        run: |
          git submodule init
          git submodule update

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Executor
        id: docker_build_executor
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile-GHA
          platforms: linux/amd64
          push: true
          target: executor
          tags: |
            hermeznetwork/zkevm-prover:${{ steps.setvars.outputs.tag }}
            hermeznetwork/zkevm-prover:${{ steps.setvars.outputs.sha_short }}

  # node-tests:
  #   needs: build-docker
  #   uses: 0xPolygonHermez/zkevm-node/.github/workflows/test-from-prover.yml@develop
  #   with:
  #     prover_image: hermeznetwork/zkevm-prover:${{needs.build-docker.outputs.image_tag}}"
  #   secrets:
  #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  #     DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
